# Generated by Django 3.2.8 on 2021-11-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('os', models.CharField(max_length=30)),
                ('domain_list', models.CharField(blank=True, max_length=300)),
                ('ports_list', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanhosts.company')),
            ],
        ),
    ]
