# Generated by Django 3.2.8 on 2021-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0005_auto_20211104_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default='2021-11-04 15:16:59'),
        ),
        migrations.AlterField(
            model_name='host',
            name='created_at',
            field=models.DateTimeField(default='2021-11-04 15:16:59'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default='2021-11-04 15:16:59'),
        ),
    ]
