# Generated by Django 3.2.8 on 2021-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0007_auto_20211107_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default='2021-11-15 16:51:46'),
        ),
        migrations.AlterField(
            model_name='host',
            name='created_at',
            field=models.DateTimeField(default='2021-11-15 16:51:46'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default='2021-11-15 16:51:46'),
        ),
    ]
