# Generated by Django 3.2.8 on 2021-11-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0008_auto_20211115_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default='2021-11-17 15:24:05'),
        ),
        migrations.AlterField(
            model_name='host',
            name='created_at',
            field=models.DateTimeField(default='2021-11-17 15:24:05'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default='2021-11-17 15:24:05'),
        ),
    ]
